# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ShoppingPad' do

end

target 'ShoppingPadTests' do

end

target 'ShoppingPadUITests' do

end

